
import { Application, BBType, BBStatus, RepoStatus, FilterTabKey, TitleStatusValue } from './types';

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: '1',
    dealer: 'LUGO AUTO GROUP',
    dealerIdNum: '6601',
    primaryName: 'PAULINO TRINIDAD DE JESUS',
    dlrId: '6101',
    br: 90,
    rsm: 'EWEBB1',
    fund: 2,
    bh: 0,
    shawAccnt: '3502312',
    bbType: BBType.TITLE_BUYBACK,
    bbStatus: BBStatus.NEW_BB_CONTACT_DEALER,
    bbDateFiled: '07/15/2024',
    bbDueDate: '08/15/2024',
    bbAmt: 10219.78,
    dpd: 6,
    insuranceStatus: "Active",
    registrationStatus: "Current",
    registrationIssueDate: "01/10/24",
    titleStatus: TitleStatusValue.RECEIVED,
    titleReceivedDate: "02/15/24",
    loanInsuranceStatus: "Customer Provided",
    repoStatus: RepoStatus.NONE,
    dlt: 53,
    currentStatusDisplay: FilterTabKey.PENDING_FILE,
    followUpDate: '07/20/2024',
    ptp: false,
    hasNote: true,
    ltrSent: false,
    isActive: true,
    internalStatus: FilterTabKey.PENDING_FILE,
    promiseToPayDate: '',
    ptpAmount: undefined,
    dealerAddressLine1: '6601/6935 65TH ST',
    dealerAddressLine2: 'SACRAMENTO CA 95828',
    dealerPhone: '9163913999',
    dealerEmail: 'FINANCE@LUGOAUTOGROUP.COM',
    dealerType: 'Franchise',
  },
  {
    id: '2',
    dealer: 'TGB GLOBAL BUSINESS LLC',
    dealerIdNum: '2451',
    primaryName: 'JOEL VALIENTE',
    dlrId: 'L215',
    br: 74,
    rsm: 'ATEIJEIRO',
    fund: 0,
    bh: 0,
    shawAccnt: '3517706',
    bbType: BBType.FIRST_PAYMENT_DEFAULT,
    bbStatus: BBStatus.PENDING_DEALER_ARRANGEMENTS,
    bbDateFiled: '07/10/2024',
    bbDueDate: '08/10/2024',
    bbAmt: 13767.21,
    dpd: -832,
    insuranceStatus: "Expired",
    registrationStatus: "Expired",
    registrationIssueDate: "12/01/23",
    titleStatus: TitleStatusValue.OUTSTANDING,
    titleReceivedDate: "",
    loanInsuranceStatus: "CPI Placed",
    repoStatus: RepoStatus.NONE,
    dlt: 47,
    currentStatusDisplay: FilterTabKey.BB_LETTER_SENT,
    followUpDate: '',
    ptp: true,
    hasNote: false,
    ltrSent: true,
    isActive: true,
    internalStatus: FilterTabKey.BB_LETTER_SENT,
    promiseToPayDate: '12/31/2025',
    ptpAmount: 500,
    dealerAddressLine1: '123 Global Ave',
    dealerAddressLine2: 'MIAMI FL 33101',
    dealerPhone: '3055551234',
    dealerEmail: 'contact@tgbglobal.com',
    dealerType: 'Non Franchise',
  },
  {
    id: '3',
    dealer: 'QUANTUM AUTO SALES',
    dealerIdNum: '13831',
    primaryName: 'GREGG NELSON',
    dlrId: 'C161',
    br: 99,
    rsm: 'GRUIZ',
    fund: 14,
    bh: 0,
    shawAccnt: '3509442',
    bbType: BBType.FIRST_PAYMENT_DEFAULT,
    bbStatus: BBStatus.PENDING_DEALER_ARRANGEMENTS,
    bbDateFiled: '06/20/2024',
    bbDueDate: '07/20/2024',
    bbAmt: 18192.14,
    dpd: -670,
    insuranceStatus: "None",
    registrationStatus: "Unknown",
    registrationIssueDate: "",
    titleStatus: TitleStatusValue.OUTSTANDING,
    titleReceivedDate: "",
    loanInsuranceStatus: "None",
    repoStatus: RepoStatus.REPOSSESSED,
    dlt: 53,
    currentStatusDisplay: FilterTabKey.DEMAND_LETTER_SENT,
    followUpDate: '07/25/2024',
    ptp: false,
    hasNote: true,
    ltrSent: true,
    isActive: true,
    internalStatus: FilterTabKey.DEMAND_LETTER_SENT,
    promiseToPayDate: '',
    ptpAmount: undefined,
    dealerAddressLine1: '456 Quantum Rd',
    dealerAddressLine2: 'AUSTIN TX 78701',
    dealerPhone: '5125555678',
    dealerEmail: 'sales@quantumautos.com',
    dealerType: 'Treat as Franchise',
  },
  {
    id: '4',
    dealer: 'TONY T CHRYSLER DODGE JEEP RAM',
    dealerIdNum: '2801',
    primaryName: 'JOELLEN BEAUSOLEIL',
    dlrId: 'L212',
    br: 75,
    rsm: 'DTAYLOR',
    fund: 0,
    bh: 0,
    shawAccnt: '3471056',
    bbType: BBType.CHOOSE_TYPE,
    bbStatus: BBStatus.BUYBACK_PAID, 
    bbDateFiled: '',
    bbDueDate: '',
    bbAmt: 18803.56,
    dpd: -55,
    insuranceStatus: "Active",
    registrationStatus: "Current",
    registrationIssueDate: "03/03/24",
    titleStatus: TitleStatusValue.RECEIVED,
    titleReceivedDate: "04/01/24",
    loanInsuranceStatus: "Customer Provided",
    repoStatus: RepoStatus.NONE,
    dlt: 41,
    currentStatusDisplay: FilterTabKey.PAID_SETTLED,
    followUpDate: '',
    ptp: false,
    hasNote: false,
    ltrSent: false,
    isActive: false,
    internalStatus: FilterTabKey.PAID_SETTLED,
    promiseToPayDate: '',
    ptpAmount: undefined,
    dealerAddressLine1: '789 Mopar St',
    dealerAddressLine2: 'ORLANDO FL 32801',
    dealerPhone: '4075558765',
    dealerEmail: 'tonyt@dealership.com',
    dealerType: 'Franchise',
  },
   {
    id: '5',
    dealer: 'ACE MOTORS',
    dealerIdNum: '7701',
    primaryName: 'JANE DOE',
    dlrId: 'A007',
    br: 50,
    rsm: 'ASMITH',
    fund: 1,
    bh: 1,
    shawAccnt: '3600123',
    bbType: BBType.COURTESY_BUYBACK,
    bbStatus: BBStatus.REFERRED_TO_LEGAL_STATUS,
    bbDateFiled: '05/01/2024',
    bbDueDate: '06/01/2024',
    bbAmt: 25000.00,
    dpd: 60,
    insuranceStatus: "Unknown",
    registrationStatus: "Unknown",
    registrationIssueDate: "",
    titleStatus: TitleStatusValue.OUTSTANDING,
    titleReceivedDate: "",
    loanInsuranceStatus: "Unknown",
    repoStatus: RepoStatus.PENDING_RECOVERY,
    dlt: 10,
    currentStatusDisplay: FilterTabKey.REFERRED_TO_LEGAL,
    followUpDate: '07/30/2024',
    ptp: false,
    hasNote: true,
    ltrSent: true,
    isActive: true,
    internalStatus: FilterTabKey.REFERRED_TO_LEGAL,
    promiseToPayDate: '',
    ptpAmount: undefined,
    dealerAddressLine1: '1 Ace Drive',
    dealerAddressLine2: 'LOS ANGELES CA 90001',
    dealerPhone: '2135551122',
    dealerEmail: 'info@acemotors.com',
    dealerType: 'Non Franchise',
  },
  {
    id: '6',
    dealer: 'LUXURY CARS INC.',
    dealerIdNum: '8802',
    primaryName: 'ALICE WONDERLAND',
    dlrId: 'L808',
    br: 88,
    rsm: 'EWEBB1',
    fund: 5,
    bh: 0,
    shawAccnt: '3701122',
    bbType: BBType.BB_LEGAL_BUYBACK,
    bbStatus: BBStatus.CORP_LEGAL,
    bbDateFiled: '07/01/2024',
    bbDueDate: '08/01/2024',
    bbAmt: 35000.50,
    dpd: 30,
    insuranceStatus: "Active",
    registrationStatus: "Current",
    registrationIssueDate: "02/15/24",
    titleStatus: TitleStatusValue.RECEIVED,
    titleReceivedDate: "03/20/24",
    loanInsuranceStatus: "Customer Provided",
    repoStatus: RepoStatus.NONE,
    dlt: 60,
    currentStatusDisplay: FilterTabKey.REFERRED_TO_LEGAL,
    followUpDate: '07/28/2024',
    ptp: true,
    hasNote: true,
    ltrSent: true,
    isActive: true,
    internalStatus: FilterTabKey.REFERRED_TO_LEGAL,
    promiseToPayDate: '08/15/2024',
    ptpAmount: 1000,
    dealerAddressLine1: '123 Luxury Lane',
    dealerAddressLine2: 'BEVERLY HILLS CA 90210',
    dealerPhone: '3105550099',
    dealerEmail: 'sales@luxurycars.com',
    dealerType: 'Franchise',
  },
  {
    id: '7',
    dealer: 'BEST VALUE MOTORS',
    dealerIdNum: '3321',
    primaryName: 'BOB BUILDER',
    dlrId: 'B101',
    br: 65,
    rsm: 'ATEIJEIRO',
    fund: 0,
    bh: 2,
    shawAccnt: '3702233',
    bbType: BBType.UNWIND,
    bbStatus: BBStatus.BUYBACK_SETTLED,
    bbDateFiled: '04/10/2024',
    bbDueDate: '05/10/2024',
    bbAmt: 8500.00,
    dpd: 0,
    insuranceStatus: "None",
    registrationStatus: "Expired",
    registrationIssueDate: "10/01/23",
    titleStatus: TitleStatusValue.OUTSTANDING,
    titleReceivedDate: "",
    loanInsuranceStatus: "CPI Placed",
    repoStatus: RepoStatus.SOLD,
    dlt: 25,
    currentStatusDisplay: FilterTabKey.PAID_SETTLED,
    followUpDate: '',
    ptp: false,
    hasNote: false,
    ltrSent: false,
    isActive: false,
    internalStatus: FilterTabKey.PAID_SETTLED,
    promiseToPayDate: '',
    ptpAmount: undefined,
    dealerAddressLine1: '456 Value Rd',
    dealerAddressLine2: 'HOUSTON TX 77001',
    dealerPhone: '7135554321',
    dealerEmail: 'bob@valuemotors.com',
    dealerType: 'Non Franchise',
  },
  {
    id: '8',
    dealer: 'SPEEDY AUTO SALES',
    dealerIdNum: '9090',
    primaryName: 'CARLA RACER',
    dlrId: 'S909',
    br: 92,
    rsm: 'GRUIZ',
    fund: 3,
    bh: 0,
    shawAccnt: '3703344',
    bbType: BBType.KBB_DISCREPANCY,
    bbStatus: BBStatus.KBB_PAID,
    bbDateFiled: '07/18/2024',
    bbDueDate: '08/18/2024',
    bbAmt: 1250.75,
    dpd: 15,
    insuranceStatus: "Active",
    registrationStatus: "Current",
    registrationIssueDate: "05/05/24",
    titleStatus: TitleStatusValue.RECEIVED,
    titleReceivedDate: "06/10/24",
    loanInsuranceStatus: "Customer Provided",
    repoStatus: RepoStatus.NONE,
    dlt: 35,
    currentStatusDisplay: FilterTabKey.PAID_SETTLED,
    followUpDate: '07/22/2024',
    ptp: false,
    hasNote: true,
    ltrSent: false,
    isActive: true,
    internalStatus: FilterTabKey.PAID_SETTLED,
    promiseToPayDate: '',
    ptpAmount: undefined,
    dealerAddressLine1: '789 Speedy Blvd',
    dealerAddressLine2: 'PHOENIX AZ 85001',
    dealerPhone: '6025556789',
    dealerEmail: 'carla@speedyauto.com',
    dealerType: 'Treat as Franchise',
  },
  {
    id: '9',
    dealer: 'FAMILY CARS LLC',
    dealerIdNum: '4001',
    primaryName: 'DAVID FAMILYMAN',
    dlrId: 'F401',
    br: 80,
    rsm: 'DTAYLOR',
    fund: 1,
    bh: 1,
    shawAccnt: '3704455',
    bbType: BBType.WARRANTY_CANCELLATION,
    bbStatus: BBStatus.WARRANTY_PAID,
    bbDateFiled: '03/01/2024',
    bbDueDate: '04/01/2024',
    bbAmt: 750.00,
    dpd: -20,
    insuranceStatus: "Expired",
    registrationStatus: "Current",
    registrationIssueDate: "11/11/23",
    titleStatus: TitleStatusValue.RECEIVED,
    titleReceivedDate: "12/15/23",
    loanInsuranceStatus: "CPI Placed",
    repoStatus: RepoStatus.NONE,
    dlt: 90,
    currentStatusDisplay: FilterTabKey.PAID_SETTLED,
    followUpDate: '',
    ptp: true,
    hasNote: false,
    ltrSent: true,
    isActive: false,
    internalStatus: FilterTabKey.PAID_SETTLED,
    promiseToPayDate: '07/25/2024',
    ptpAmount: 200,
    dealerAddressLine1: '101 Family Rd',
    dealerAddressLine2: 'CHICAGO IL 60601',
    dealerPhone: '3125551123',
    dealerEmail: 'david@familycars.com',
    dealerType: 'Non Franchise',
  },
  {
    id: '10',
    dealer: 'GREEN WHEELS AUTO',
    dealerIdNum: '5050',
    primaryName: 'EVA GREEN',
    dlrId: 'G505',
    br: 70,
    rsm: 'ASMITH',
    fund: 0,
    bh: 0,
    shawAccnt: '3705566',
    bbType: BBType.TITLE_BUYBACK,
    bbStatus: BBStatus.SECURED_TITLE,
    bbDateFiled: '06/01/2024',
    bbDueDate: '07/01/2024',
    bbAmt: 19500.00,
    dpd: 45,
    insuranceStatus: "Active",
    registrationStatus: "Current",
    registrationIssueDate: "04/01/24",
    titleStatus: TitleStatusValue.RECEIVED,
    titleReceivedDate: "05/15/24",
    loanInsuranceStatus: "Customer Provided",
    repoStatus: RepoStatus.PENDING_RECOVERY,
    dlt: 15,
    currentStatusDisplay: FilterTabKey.PENDING_FILE,
    followUpDate: '08/01/2024',
    ptp: false,
    hasNote: true,
    ltrSent: true,
    isActive: true,
    internalStatus: FilterTabKey.PENDING_FILE,
    promiseToPayDate: '',
    ptpAmount: undefined,
    dealerAddressLine1: '202 Green St',
    dealerAddressLine2: 'SEATTLE WA 98101',
    dealerPhone: '2065552233',
    dealerEmail: 'eva@greenwheels.com',
    dealerType: 'Franchise',
  },
];

export const TAB_KEYS_ORDER: FilterTabKey[] = [
  FilterTabKey.ALL,
  FilterTabKey.PENDING_FILE,
  FilterTabKey.BB_LETTER_SENT,
  FilterTabKey.DEMAND_LETTER_SENT,
  FilterTabKey.FORCED_ACH_PROCESSED,
  FilterTabKey.REFERRED_TO_LEGAL,
  FilterTabKey.PAID_SETTLED,
];

export const TAB_MOCK_COUNTS: Record<FilterTabKey, number> = {
    [FilterTabKey.ALL]: 5365, // This will be dynamically updated based on actual count
    [FilterTabKey.PENDING_FILE]: 124,
    [FilterTabKey.BB_LETTER_SENT]: 694,
    [FilterTabKey.DEMAND_LETTER_SENT]: 9,
    [FilterTabKey.FORCED_ACH_PROCESSED]: 0,
    [FilterTabKey.REFERRED_TO_LEGAL]: 114,
    [FilterTabKey.PAID_SETTLED]: 4423,
};

export const BB_TYPE_OPTIONS = Object.values(BBType);
export const BB_STATUS_OPTIONS = Object.values(BBStatus);

// Filtered list of BBType options for the multi-select dropdown, excluding "Choose Type"
export const BB_TYPE_FILTER_OPTIONS = Object.values(BBType).filter(
  type => type !== BBType.CHOOSE_TYPE
);

// Filtered list of BBStatus options for the multi-select dropdown, excluding "Choose Status"
export const BB_STATUS_FILTER_OPTIONS = Object.values(BBStatus).filter(
  status => status !== BBStatus.CHOOSE_STATUS
);

export const REPO_STATUS_OPTIONS = Object.values(RepoStatus);
// If TitleStatusValue needs to be an editable dropdown option list later:
// export const TITLE_STATUS_OPTIONS = Object.values(TitleStatusValue);
